language: php
php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly

branches:
  only:
  - master
  - travis

before_install:
  - pecl install --nodeps psr

install:
  - phpize
  - ./configure
  - make

before_script:
  make install

script:
  make test

after_failure:
  - |
    for LOG in $(find tests -name '*.log'); do
      echo $LOG
      tail -n +2 $LOG
      echo
    done

