language: php
php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

branches:
  only:
  - master

before_install:
  - pecl install psr

install:
  - phpize
  - ./configure
  - make

before_script:
  make install

script:
  make test

