language: php
php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly

branches:
  only:
  - master
  - travis
  - /^v\d+\.\d+\.\d+$/

before_install:
  - pecl install --nodeps psr

install:
  - phpize
  - ./configure
  - make

before_script:
  make install

script:
  make test

after_failure:
  - |
    for FILE in $(find tests -name '*.diff'); do
      echo $FILE
      cat FILE
      echo
    done

before_deploy:
  - openssl aes-256-cbc -K $encrypted_36ea4391f664_key -iv $encrypted_36ea4391f664_iv -in sign.gpg.enc -out sign.gpg -d
  - gpg --import sign.gpg
  - rm sign.gpg
  - pecl package
  - export RELEASE_PACKAGE=$(ls http_message-*.tgz)
#  - echo | pecl sign "$RELEASE_PACKAGE"

deploy:
  provider: releases
  api_key:
    secure: "HuYxK89LGMINNzDyrA9xXVzQB7YKo563Q1EVkAOrrv7cDKbfVLTPHfI9huB8XnzDJgp1EhrXA3hMKeJdpbtzoEhiaVDc/eeFcCubhf+VEsMbke9TOYIEx7mSNDpV0igyWDR1bt+8GrCFkP04NMzzlqU+KoW0ceK/xCaMRhNWiskf3Z+e2Xne3yEVd64A61xtyPMbaOIqqmjkmqCyrN9DT+5g+zZVMz1UssdfRqMCKTyHcaYYFayQwSZgmAxZO3WKoHnd5ydoii2XIBHto7RESqAoyemw/Ksw7YdplxsZMfbCsmiSuwrlmd1t/BX7QIULeJsVwPiv7MWJWjh8VRIiFCw5FdZ+n2kLfL32MY8r4hl7Uo9nEkNaIYRBX0ryV5XXRU/2q1nuz8Knaz++Q+tPodmMp8vzmDGl2cguq9KuKbVEbiFjR+PO96YFlKdtDosUQFjbSbQOFDQdstPFSZr5s/PKPVj5Va33PyyrLI9TMZwgWLPzMEqerGXy8meigeZ0r0m3DG4slzxhxE9y30fFEx9fWPNR3AN/1NGi7WTsqonPQitu1M7YyKCdMqjWJkr++geapJwKVX/poxExQ4i0TEkgqGWmV9nJehGJ5nS8s2tH4PR8+3bA2gvNoqBO+jmd8CLjkPGbCPu8OlvdwXmeKJYsX382iGG8CxrDDPhGlr4="
  file: "$RELEASE_PACKAGE"
  skip_cleanup: true
  name: "$TRAVIS_TAG"
  prerelease: true
  on:
    tags: true
